spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT54332}/${DB_NAME:iam_db}
    username: ${POSTGRES_USER:iam_user}
    password: ${POSTGRES_PASSWORD:dev_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    vault:
      enabled: false
