spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_db
    username: iam_malak
    password: Malak123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    vault:
      enabled: false